//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UDEOExceptionless
{
    using System;
    using System.Collections.Generic;
    
    public partial class Balance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Balance()
        {
            this.Donacion_balance = new HashSet<Donacion_balance1>();
        }
    
        public int Id { get; set; }
        public decimal Gastos { get; set; }
        public decimal Publicidad { get; set; }
        public decimal Caja_chica { get; set; }
        public decimal Iva { get; set; }
        public decimal Isr { get; set; }
        public decimal Total { get; set; }
        public string Mes { get; set; }
        public string Anio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donacion_balance1> Donacion_balance { get; set; }
    }
}
