//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UDEOExceptionless
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Donacion()
        {
            this.donacion_balance = new HashSet<donacion_balance>();
        }
    
        public int Id { get; set; }
        public int Cliente_id { get; set; }
        public decimal Mes { get; set; }
        public decimal Anio { get; set; }
        public decimal Donacion1 { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<donacion_balance> donacion_balance { get; set; }
    }
}
